const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./endpoints.js"];
const data = require("./data/products.json");

const doc = {
  info: {
    version: "1.0.0",
    title: "WW API",
    description:
      "Documentation automatically generated by the <b>swagger.autogen</b> module.",
  },
  host: "ww.lndo.site:80",
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Products",
      description: "Endpoints",
    },
  ],
  definitions: {
    Product: data[0],
    Products: data,
    AddProduct: {
      data: data[0],
    },
    DeleteProduct: {
      $id: 1,
    },
    UpdateProduct: {
      $id: 1,
      data: data[0],
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
